// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { CheckTaskApiTasksTaskIdCheckPostData, CheckTaskApiTasksTaskIdCheckPostErrors, CheckTaskApiTasksTaskIdCheckPostResponses, DeleteTaskApiTasksTaskIdDeleteData, DeleteTaskApiTasksTaskIdDeleteErrors, DeleteTaskApiTasksTaskIdDeleteResponses, GetDefiniteTaskApiTasksTaskIdGetData, GetDefiniteTaskApiTasksTaskIdGetErrors, GetDefiniteTaskApiTasksTaskIdGetResponses, GetLeaderboardApiPvpRatingLeaderboardGetData, GetLeaderboardApiPvpRatingLeaderboardGetErrors, GetLeaderboardApiPvpRatingLeaderboardGetResponses, GetQueueStatusApiPvpQueueStatusGetData, GetQueueStatusApiPvpQueueStatusGetResponses, GetRecentMatchesApiPvpMatchesRecentGetData, GetRecentMatchesApiPvpMatchesRecentGetErrors, GetRecentMatchesApiPvpMatchesRecentGetResponses, GetTasksApiTasksGetData, GetTasksApiTasksGetResponses, GetTasksToJsonApiTasksExportGetData, GetTasksToJsonApiTasksExportGetResponses, LogInUserApiUserLoginPostData, LogInUserApiUserLoginPostErrors, LogInUserApiUserLoginPostResponses, PostTasksApiTasksUploadImportJsonPostData, PostTasksApiTasksUploadImportJsonPostErrors, PostTasksApiTasksUploadImportJsonPostResponses, PostTasksApiTasksUploadPostData, PostTasksApiTasksUploadPostErrors, PostTasksApiTasksUploadPostResponses, RegistrationUserApiUserCreatePostData, RegistrationUserApiUserCreatePostErrors, RegistrationUserApiUserCreatePostResponses, UpdateTaskApiTasksTaskIdPatchData, UpdateTaskApiTasksTaskIdPatchErrors, UpdateTaskApiTasksTaskIdPatchResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Registration User
 */
export const registrationUserApiUserCreatePost = <ThrowOnError extends boolean = false>(options: Options<RegistrationUserApiUserCreatePostData, ThrowOnError>) => (options.client ?? client).post<RegistrationUserApiUserCreatePostResponses, RegistrationUserApiUserCreatePostErrors, ThrowOnError>({
    url: '/api/user/create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Log In User
 */
export const logInUserApiUserLoginPost = <ThrowOnError extends boolean = false>(options: Options<LogInUserApiUserLoginPostData, ThrowOnError>) => (options.client ?? client).post<LogInUserApiUserLoginPostResponses, LogInUserApiUserLoginPostErrors, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    url: '/api/user/login',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

/**
 * Post Tasks
 *
 * making tasks (withowt admin check yet)
 */
export const postTasksApiTasksUploadPost = <ThrowOnError extends boolean = false>(options: Options<PostTasksApiTasksUploadPostData, ThrowOnError>) => (options.client ?? client).post<PostTasksApiTasksUploadPostResponses, PostTasksApiTasksUploadPostErrors, ThrowOnError>({
    url: '/api/tasks/upload',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post Tasks
 *
 * import files from json
 */
export const postTasksApiTasksUploadImportJsonPost = <ThrowOnError extends boolean = false>(options: Options<PostTasksApiTasksUploadImportJsonPostData, ThrowOnError>) => (options.client ?? client).post<PostTasksApiTasksUploadImportJsonPostResponses, PostTasksApiTasksUploadImportJsonPostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/tasks/upload/import/json',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Check Task
 *
 * Check user answer for task
 */
export const checkTaskApiTasksTaskIdCheckPost = <ThrowOnError extends boolean = false>(options: Options<CheckTaskApiTasksTaskIdCheckPostData, ThrowOnError>) => (options.client ?? client).post<CheckTaskApiTasksTaskIdCheckPostResponses, CheckTaskApiTasksTaskIdCheckPostErrors, ThrowOnError>({
    url: '/api/tasks/{task_id}/check',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Task
 *
 * Delete tasks by id
 */
export const deleteTaskApiTasksTaskIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteTaskApiTasksTaskIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteTaskApiTasksTaskIdDeleteResponses, DeleteTaskApiTasksTaskIdDeleteErrors, ThrowOnError>({ url: '/api/tasks/{task_id}', ...options });

/**
 * Get Definite Task
 *
 * get definite task by id
 */
export const getDefiniteTaskApiTasksTaskIdGet = <ThrowOnError extends boolean = false>(options: Options<GetDefiniteTaskApiTasksTaskIdGetData, ThrowOnError>) => (options.client ?? client).get<GetDefiniteTaskApiTasksTaskIdGetResponses, GetDefiniteTaskApiTasksTaskIdGetErrors, ThrowOnError>({ url: '/api/tasks/{task_id}', ...options });

/**
 * Update Task
 *
 * edit task by id
 */
export const updateTaskApiTasksTaskIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateTaskApiTasksTaskIdPatchData, ThrowOnError>) => (options.client ?? client).patch<UpdateTaskApiTasksTaskIdPatchResponses, UpdateTaskApiTasksTaskIdPatchErrors, ThrowOnError>({
    url: '/api/tasks/{task_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Tasks
 *
 * get all tasks
 */
export const getTasksApiTasksGet = <ThrowOnError extends boolean = false>(options?: Options<GetTasksApiTasksGetData, ThrowOnError>) => (options?.client ?? client).get<GetTasksApiTasksGetResponses, unknown, ThrowOnError>({ url: '/api/tasks/', ...options });

/**
 * Get Tasks To Json
 *
 * export files into json
 */
export const getTasksToJsonApiTasksExportGet = <ThrowOnError extends boolean = false>(options?: Options<GetTasksToJsonApiTasksExportGetData, ThrowOnError>) => (options?.client ?? client).get<GetTasksToJsonApiTasksExportGetResponses, unknown, ThrowOnError>({ url: '/api/tasks/export', ...options });

/**
 * Get Queue Status
 */
export const getQueueStatusApiPvpQueueStatusGet = <ThrowOnError extends boolean = false>(options?: Options<GetQueueStatusApiPvpQueueStatusGetData, ThrowOnError>) => (options?.client ?? client).get<GetQueueStatusApiPvpQueueStatusGetResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/pvp/queue-status',
    ...options
});

/**
 * Get Recent Matches
 *
 * Get user's recent PvP matches.
 */
export const getRecentMatchesApiPvpMatchesRecentGet = <ThrowOnError extends boolean = false>(options?: Options<GetRecentMatchesApiPvpMatchesRecentGetData, ThrowOnError>) => (options?.client ?? client).get<GetRecentMatchesApiPvpMatchesRecentGetResponses, GetRecentMatchesApiPvpMatchesRecentGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/pvp/matches/recent',
    ...options
});

/**
 * Get Leaderboard
 */
export const getLeaderboardApiPvpRatingLeaderboardGet = <ThrowOnError extends boolean = false>(options?: Options<GetLeaderboardApiPvpRatingLeaderboardGetData, ThrowOnError>) => (options?.client ?? client).get<GetLeaderboardApiPvpRatingLeaderboardGetResponses, GetLeaderboardApiPvpRatingLeaderboardGetErrors, ThrowOnError>({ url: '/api/pvp/rating-leaderboard', ...options });
