// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://solaris.sherstd.ru' | (string & {});
};

/**
 * Body_log_in_user_api_user_login_post
 */
export type BodyLogInUserApiUserLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_post_tasks_api_tasks_upload_import_json_post
 */
export type BodyPostTasksApiTasksUploadImportJsonPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * CheckAnswer
 */
export type CheckAnswer = {
    /**
     * Answer
     */
    answer: string;
};

/**
 * Difficulty
 */
export type Difficulty = 'лёгкий' | 'средний' | 'сложный';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * TaskSchema
 */
export type TaskSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Subject
     */
    subject: string;
    theme: Theme;
    difficulty: Difficulty;
    /**
     * Title
     */
    title: string;
    /**
     * Task Text
     */
    task_text: string;
    /**
     * Hint
     */
    hint?: string | null;
    /**
     * Answer
     */
    answer?: string | null;
    /**
     * Is Published
     */
    is_published?: boolean;
};

/**
 * Theme
 */
export type Theme = 'математика' | 'русский' | 'информатика' | 'физика';

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * UserLogIn
 */
export type UserLogIn = {
    /**
     * User Token
     */
    user_token: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Elo Rating
     */
    elo_rating: number;
    /**
     * Is Blocked
     */
    is_blocked: boolean;
};

/**
 * UserSchema
 */
export type UserSchema = {
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Password
     */
    password: string;
    /**
     * Email
     */
    email: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type RegistrationUserApiUserCreatePostData = {
    body: UserSchema;
    path?: never;
    query?: never;
    url: '/api/user/create';
};

export type RegistrationUserApiUserCreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegistrationUserApiUserCreatePostError = RegistrationUserApiUserCreatePostErrors[keyof RegistrationUserApiUserCreatePostErrors];

export type RegistrationUserApiUserCreatePostResponses = {
    /**
     * Successful Response
     */
    200: UserLogIn;
};

export type RegistrationUserApiUserCreatePostResponse = RegistrationUserApiUserCreatePostResponses[keyof RegistrationUserApiUserCreatePostResponses];

export type LogInUserApiUserLoginPostData = {
    body: BodyLogInUserApiUserLoginPost;
    path?: never;
    query?: never;
    url: '/api/user/login';
};

export type LogInUserApiUserLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogInUserApiUserLoginPostError = LogInUserApiUserLoginPostErrors[keyof LogInUserApiUserLoginPostErrors];

export type LogInUserApiUserLoginPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LogInUserApiUserLoginPostResponse = LogInUserApiUserLoginPostResponses[keyof LogInUserApiUserLoginPostResponses];

export type GetUserByTokenApiUserTokenGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/token';
};

export type GetUserByTokenApiUserTokenGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetUserByTokenApiUserTokenGetResponse = GetUserByTokenApiUserTokenGetResponses[keyof GetUserByTokenApiUserTokenGetResponses];

export type GetUserByIdApiUserUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/user/{user_id}';
};

export type GetUserByIdApiUserUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserByIdApiUserUserIdGetError = GetUserByIdApiUserUserIdGetErrors[keyof GetUserByIdApiUserUserIdGetErrors];

export type GetUserByIdApiUserUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetUserByIdApiUserUserIdGetResponse = GetUserByIdApiUserUserIdGetResponses[keyof GetUserByIdApiUserUserIdGetResponses];

export type GetAllUsersApiUserGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user';
};

export type GetAllUsersApiUserGetResponses = {
    /**
     * Response Get All Users Api User Get
     *
     * Successful Response
     */
    200: Array<UserResponse>;
};

export type GetAllUsersApiUserGetResponse = GetAllUsersApiUserGetResponses[keyof GetAllUsersApiUserGetResponses];

export type PostTasksApiTasksUploadPostData = {
    body: TaskSchema;
    path?: never;
    query?: never;
    url: '/api/tasks/upload';
};

export type PostTasksApiTasksUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostTasksApiTasksUploadPostError = PostTasksApiTasksUploadPostErrors[keyof PostTasksApiTasksUploadPostErrors];

export type PostTasksApiTasksUploadPostResponses = {
    /**
     * Successful Response
     */
    200: TaskSchema;
};

export type PostTasksApiTasksUploadPostResponse = PostTasksApiTasksUploadPostResponses[keyof PostTasksApiTasksUploadPostResponses];

export type PostTasksApiTasksUploadImportJsonPostData = {
    body: BodyPostTasksApiTasksUploadImportJsonPost;
    path?: never;
    query?: never;
    url: '/api/tasks/upload/import/json';
};

export type PostTasksApiTasksUploadImportJsonPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostTasksApiTasksUploadImportJsonPostError = PostTasksApiTasksUploadImportJsonPostErrors[keyof PostTasksApiTasksUploadImportJsonPostErrors];

export type PostTasksApiTasksUploadImportJsonPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CheckTaskApiTasksTaskIdCheckPostData = {
    body: CheckAnswer;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/tasks/{task_id}/check';
};

export type CheckTaskApiTasksTaskIdCheckPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckTaskApiTasksTaskIdCheckPostError = CheckTaskApiTasksTaskIdCheckPostErrors[keyof CheckTaskApiTasksTaskIdCheckPostErrors];

export type CheckTaskApiTasksTaskIdCheckPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteTaskApiTasksTaskIdDeleteData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/tasks/{task_id}';
};

export type DeleteTaskApiTasksTaskIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTaskApiTasksTaskIdDeleteError = DeleteTaskApiTasksTaskIdDeleteErrors[keyof DeleteTaskApiTasksTaskIdDeleteErrors];

export type DeleteTaskApiTasksTaskIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateTaskApiTasksTaskIdPatchData = {
    body: TaskSchema;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/tasks/{task_id}';
};

export type UpdateTaskApiTasksTaskIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTaskApiTasksTaskIdPatchError = UpdateTaskApiTasksTaskIdPatchErrors[keyof UpdateTaskApiTasksTaskIdPatchErrors];

export type UpdateTaskApiTasksTaskIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTasksApiTasksGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tasks/';
};

export type GetTasksApiTasksGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetDefiniteTaskApiTasksGetTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/tasks/get/{task_id}';
};

export type GetDefiniteTaskApiTasksGetTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDefiniteTaskApiTasksGetTaskIdGetError = GetDefiniteTaskApiTasksGetTaskIdGetErrors[keyof GetDefiniteTaskApiTasksGetTaskIdGetErrors];

export type GetDefiniteTaskApiTasksGetTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTasksToJsonApiTasksExportGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tasks/export';
};

export type GetTasksToJsonApiTasksExportGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetQueueStatusApiPvpQueueStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/pvp/queue-status';
};

export type GetQueueStatusApiPvpQueueStatusGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRecentMatchesApiPvpMatchesRecentGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/pvp/matches/recent';
};

export type GetRecentMatchesApiPvpMatchesRecentGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRecentMatchesApiPvpMatchesRecentGetError = GetRecentMatchesApiPvpMatchesRecentGetErrors[keyof GetRecentMatchesApiPvpMatchesRecentGetErrors];

export type GetRecentMatchesApiPvpMatchesRecentGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetLeaderboardApiPvpRatingLeaderboardGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/pvp/rating-leaderboard';
};

export type GetLeaderboardApiPvpRatingLeaderboardGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLeaderboardApiPvpRatingLeaderboardGetError = GetLeaderboardApiPvpRatingLeaderboardGetErrors[keyof GetLeaderboardApiPvpRatingLeaderboardGetErrors];

export type GetLeaderboardApiPvpRatingLeaderboardGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTasksApiTrainingGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Subject
         */
        subject?: string | null;
        /**
         * Theme
         */
        theme?: Theme | null;
        /**
         * Difficulty
         */
        difficulty?: Difficulty | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Skip
         */
        skip?: number;
    };
    url: '/api/training/';
};

export type GetTasksApiTrainingGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTasksApiTrainingGetError = GetTasksApiTrainingGetErrors[keyof GetTasksApiTrainingGetErrors];

export type GetTasksApiTrainingGetResponses = {
    /**
     * Response Get Tasks Api Training  Get
     *
     * Successful Response
     */
    200: Array<TaskSchema>;
};

export type GetTasksApiTrainingGetResponse = GetTasksApiTrainingGetResponses[keyof GetTasksApiTrainingGetResponses];

export type GetTaskHintApiTrainingTaskTaskIdHintGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/training/task/{task_id}/hint';
};

export type GetTaskHintApiTrainingTaskTaskIdHintGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskHintApiTrainingTaskTaskIdHintGetError = GetTaskHintApiTrainingTaskTaskIdHintGetErrors[keyof GetTaskHintApiTrainingTaskTaskIdHintGetErrors];

export type GetTaskHintApiTrainingTaskTaskIdHintGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CheckAnswerApiTrainingTaskTaskIdCheckPostData = {
    body: CheckAnswer;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/training/task/{task_id}/check';
};

export type CheckAnswerApiTrainingTaskTaskIdCheckPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckAnswerApiTrainingTaskTaskIdCheckPostError = CheckAnswerApiTrainingTaskTaskIdCheckPostErrors[keyof CheckAnswerApiTrainingTaskTaskIdCheckPostErrors];

export type CheckAnswerApiTrainingTaskTaskIdCheckPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
